application: happytransportnz
version: 2
runtime: python27
api_version : 1
threadsafe: true

builtins:
- remote_api: on
- appstats: on

handlers:

- url: /static
  static_dir: core/static

- url: .*
  script: core.app
